apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 1          
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      hostNetwork: true
      restartPolicy: Always
      containers:
      - name: studentapp
        image: studentapp
        imagePullPolicy: Never
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081

        volumeMounts:
        - name: student-log
          mountPath: /var/log/apps

      volumes:
      - name: student-log
        hostPath:
          path: /var/log/apps

---

apiVersion: v1
kind: Service
metadata:
  name: serviceapp
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort : 31001
    
