apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      restartPolicy: Always
      containers:
      - name: studentapp
        image: studentapp
        imagePullPolicy: IfNotPresent
        resources:
           requests:
             cpu: 250m
             memory: 500Mi
           limits:
             cpu: 500m
             memory: 1Gi
        ports:
        - containerPort: 8081

        volumeMounts:
        - name: student-log
          mountPath: /var/log/apps

      volumes:
      - name: student-log
        hostPath:
          path: /var/log/apps

---

apiVersion: v1
kind: Service
metadata:
  name: serviceapp
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081

    
